import { copyFileSync, existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs'
import path from 'node:path'

// apps are discovered by the caller (cli manifest)

function q(value) {
  return JSON.stringify(String(value ?? ''))
}

function jsxText(value) {
  return String(value ?? '')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/\{/g, '&#123;')
    .replace(/\}/g, '&#125;')
}

function readJson(file) {
  return JSON.parse(readFileSync(file, 'utf8'))
}

function preferredIcon(app) {
  for (const size of ['64', '128', '32', '256', '512']) {
    if (app.icons[size]) return { size, file: app.icons[size] }
  }
  return null
}

function configuredLauncherAppIds(repoRoot) {
  const manifestPath = path.join(repoRoot, 'apps', 'app-launcher', 'package.json')
  if (!existsSync(manifestPath)) return null
  const manifest = readJson(manifestPath)
  const ids = manifest?.gea?.launcherCatalog?.appIds
  return Array.isArray(ids) ? ids.map((id) => String(id).trim()).filter(Boolean) : null
}

function orderedIncludeFilter(apps, includeAppIds) {
  if (!includeAppIds || includeAppIds.length === 0) return apps
  const byId = new Map(apps.map((app) => [app.id, app]))
  return includeAppIds.map((id) => byId.get(id)).filter(Boolean)
}

function launcherApps(allApps, target, includeAppIds = null) {
  const apps = allApps
    .filter((app) => app.runtime === 'gea')
    .filter((app) => app.targets?.[target] === true)
    .filter((app) => app.launcher.hidden !== true)
    .sort((a, b) => {
      const order = a.launcher.order - b.launcher.order
      return order || a.name.localeCompare(b.name)
    })
  return orderedIncludeFilter(apps, includeAppIds)
}

function copyLauncherIcon({ repoRoot, app, outputFile }) {
  const icon = preferredIcon(app)
  if (!icon) return ''
  const sourcePath = path.resolve(repoRoot, app.root, icon.file)
  if (!existsSync(sourcePath)) return ''
  const iconsDir = path.join(path.dirname(outputFile), 'icons')
  mkdirSync(iconsDir, { recursive: true })
  const ext = path.extname(icon.file).toLowerCase() || '.png'
  const outputName = `${app.id}-${icon.size}${ext}`
  copyFileSync(sourcePath, path.join(iconsDir, outputName))
  return `generated/icons/${outputName}`
}

export function generateLauncherCatalog({ repoRoot, apps: allApps, target = 'geaos', outputFile }) {
  if (!repoRoot) throw new Error('generateLauncherCatalog requires repoRoot')
  if (!Array.isArray(allApps)) throw new Error('generateLauncherCatalog requires apps')
  if (!outputFile) throw new Error('generateLauncherCatalog requires outputFile')
  const includeAppIds = configuredLauncherAppIds(repoRoot)
  const apps = launcherApps(allApps, target, includeAppIds)
  const generatedDir = path.dirname(outputFile)
  rmSync(path.join(generatedDir, 'icons'), { recursive: true, force: true })
  mkdirSync(generatedDir, { recursive: true })

  const lines = [
    '// Auto-generated by gea apps launcher. Do not edit.',
    "import { Apps } from '@geastack/core'",
    "import '../components/LauncherButton.css'",
    '',
    'export function LauncherCatalog() {',
    '  return (',
    '    <div class="launcher-list" momentum>'
  ]

  for (const app of apps) {
    const iconSrc = copyLauncherIcon({ repoRoot, app, outputFile })
    const style = app.launcher.accent ? ` style={{ borderColor: ${q(app.launcher.accent)} }}` : ''
    lines.push(`      <div class="launcher-card"${style} onClick={() => Apps.launch(${q(app.id)})}>`)
    if (iconSrc) {
      lines.push(`        <img class="launcher-card-icon" src=${q(iconSrc)} />`)
    } else {
      lines.push('        <div class="launcher-card-icon launcher-card-icon-placeholder" />')
    }
    lines.push(
      '        <div class="launcher-card-copy">',
      `          <span class="launcher-card-title">${jsxText(app.name)}</span>`,
      '        </div>',
      '      </div>'
    )
  }

  lines.push(
    '    </div>',
    '  )',
    '}',
    ''
  )
  writeFileSync(outputFile, `${lines.join('\n')}`)
  return apps
}
